name: Cargo Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Cargo Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo check
        run: cargo check --all-features