name: Format Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  RUST_BACKTRACE: 1

jobs:
  fmt:
    name: Rust Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check